#!/usr/bin/env bash
set -Eeuo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
STATE_FILE="${LAYA_SAGEMAKER_STATE_FILE:-$ROOT/sagemaker/.deployment.env}"
DEFAULT_REQUEST="$ROOT/sagemaker/request.json"

AWS_REGION="${AWS_REGION:-${AWS_DEFAULT_REGION:-us-west-2}}"
AWS_PROFILE="${AWS_PROFILE:-}"
SAGEMAKER_ROLE_ARN="${SAGEMAKER_ROLE_ARN:-}"
INSTANCE_TYPE="${INSTANCE_TYPE:-ml.m5.xlarge}"
ECR_REPOSITORY="${ECR_REPOSITORY:-laya-sagemaker}"
NAME_PREFIX="${NAME_PREFIX:-laya}"
PLATFORM="${PLATFORM:-linux/amd64}"

usage() {
  cat <<'EOF'
Usage: ./sagemaker/manage.sh <command> [arguments]

Commands:
  deploy                  Build, push, and deploy a real-time endpoint
  status                  Show the current endpoint status
  invoke [request] [out]  Invoke the endpoint with a JSON request
  logs [since]            Tail CloudWatch logs (default: 1h)
  cleanup                 Delete endpoint, endpoint config, and model

Required for deploy:
  SAGEMAKER_ROLE_ARN      Existing SageMaker execution-role ARN

Optional:
  AWS_PROFILE             AWS CLI profile (omit to use the default chain)
  AWS_REGION              Deployment region (default: us-west-2)
  INSTANCE_TYPE           Endpoint instance type (default: ml.m5.xlarge)
  ECR_REPOSITORY          ECR repository name (default: laya-sagemaker)
  NAME_PREFIX             Resource-name prefix (default: laya)
  LAYA_MODEL_REVISION     Hugging Face commit or tag to pin
  DELETE_ECR_REPOSITORY   Set to 1 during cleanup to remove ECR images
EOF
}

die() {
  printf 'Error: %s\n' "$*" >&2
  exit 1
}

require_command() {
  command -v "$1" >/dev/null 2>&1 || die "Required command not found: $1"
}

aws_cli() {
  local global_args=(--region "$AWS_REGION")
  if [[ -n "$AWS_PROFILE" ]]; then
    global_args+=(--profile "$AWS_PROFILE")
  fi
  command aws "${global_args[@]}" "$@"
}

resource_exists() {
  local output
  if output="$(aws_cli "$@" 2>&1)"; then
    return 0
  fi
  if grep -Eqi 'could not find|not found|does not exist' <<<"$output"; then
    return 1
  fi
  printf '%s\n' "$output" >&2
  return 2
}

save_state() {
  umask 077
  {
    printf 'AWS_REGION=%q\n' "$AWS_REGION"
    printf 'AWS_PROFILE=%q\n' "$AWS_PROFILE"
    printf 'ECR_REPOSITORY=%q\n' "$ECR_REPOSITORY"
    printf 'INSTANCE_TYPE=%q\n' "$INSTANCE_TYPE"
    printf 'IMAGE_TAG=%q\n' "$IMAGE_TAG"
    printf 'IMAGE_URI=%q\n' "$IMAGE_URI"
    printf 'IMAGE_DIGEST=%q\n' "${IMAGE_DIGEST:-}"
    printf 'MODEL_NAME=%q\n' "$MODEL_NAME"
    printf 'ENDPOINT_CONFIG_NAME=%q\n' "$ENDPOINT_CONFIG_NAME"
    printf 'ENDPOINT_NAME=%q\n' "$ENDPOINT_NAME"
  } >"$STATE_FILE"
}

load_state() {
  [[ -f "$STATE_FILE" ]] || die "Deployment state not found: $STATE_FILE"
  # The file is generated by save_state() with shell-escaped values.
  # shellcheck disable=SC1090
  source "$STATE_FILE"
}

deploy() {
  [[ -n "$SAGEMAKER_ROLE_ARN" ]] || die "Set SAGEMAKER_ROLE_ARN to an existing SageMaker execution role"
  [[ ! -f "$STATE_FILE" ]] || die "Deployment state already exists. Run cleanup or move $STATE_FILE first"

  require_command aws
  require_command docker
  require_command uv

  local stamp account_id registry local_image
  stamp="$(date -u +%Y%m%d-%H%M%S)"
  MODEL_NAME="${NAME_PREFIX}-model-${stamp}"
  ENDPOINT_CONFIG_NAME="${NAME_PREFIX}-config-${stamp}"
  ENDPOINT_NAME="${NAME_PREFIX}-endpoint-${stamp}"
  IMAGE_TAG="$stamp"

  account_id="$(aws_cli sts get-caller-identity --query Account --output text)"
  [[ "$account_id" =~ ^[0-9]{12}$ ]] || die "Could not determine the AWS account ID"
  registry="${account_id}.dkr.ecr.${AWS_REGION}.amazonaws.com"
  IMAGE_URI="${registry}/${ECR_REPOSITORY}:${IMAGE_TAG}"
  local_image="${ECR_REPOSITORY}:${IMAGE_TAG}"
  IMAGE_DIGEST=""
  save_state

  printf 'Preparing the Laya checkpoint...\n'
  uv run python "$ROOT/sagemaker/prepare_model.py"

  if ! aws_cli ecr describe-repositories --repository-names "$ECR_REPOSITORY" >/dev/null 2>&1; then
    aws_cli ecr create-repository \
      --repository-name "$ECR_REPOSITORY" \
      --image-scanning-configuration scanOnPush=true \
      --image-tag-mutability IMMUTABLE >/dev/null
  fi

  aws_cli ecr get-login-password | docker login --username AWS --password-stdin "$registry"

  printf 'Building %s for %s...\n' "$local_image" "$PLATFORM"
  docker buildx build \
    --platform "$PLATFORM" \
    --load \
    --file "$ROOT/sagemaker/Dockerfile" \
    --tag "$local_image" \
    "$ROOT"

  docker tag "$local_image" "$IMAGE_URI"
  docker push "$IMAGE_URI"
  IMAGE_DIGEST="$(aws_cli ecr describe-images \
    --repository-name "$ECR_REPOSITORY" \
    --image-ids imageTag="$IMAGE_TAG" \
    --query 'imageDetails[0].imageDigest' \
    --output text)"
  save_state

  aws_cli sagemaker create-model \
    --model-name "$MODEL_NAME" \
    --execution-role-arn "$SAGEMAKER_ROLE_ARN" \
    --primary-container "Image=${IMAGE_URI},Mode=SingleModel" \
    --enable-network-isolation >/dev/null

  aws_cli sagemaker create-endpoint-config \
    --endpoint-config-name "$ENDPOINT_CONFIG_NAME" \
    --production-variants \
      "VariantName=AllTraffic,ModelName=${MODEL_NAME},InitialInstanceCount=1,InstanceType=${INSTANCE_TYPE},InitialVariantWeight=1" >/dev/null

  aws_cli sagemaker create-endpoint \
    --endpoint-name "$ENDPOINT_NAME" \
    --endpoint-config-name "$ENDPOINT_CONFIG_NAME" >/dev/null

  printf 'Waiting for endpoint %s to enter InService...\n' "$ENDPOINT_NAME"
  if ! aws_cli sagemaker wait endpoint-in-service --endpoint-name "$ENDPOINT_NAME"; then
    aws_cli sagemaker describe-endpoint --endpoint-name "$ENDPOINT_NAME" || true
    die "Endpoint did not enter InService. State retained for status or cleanup"
  fi

  aws_cli sagemaker describe-endpoint \
    --endpoint-name "$ENDPOINT_NAME" \
    --query '{EndpointName:EndpointName,Status:EndpointStatus}'
  printf 'Instance type: %s\n' "$INSTANCE_TYPE"

  printf '\nDeployment state: %s\n' "$STATE_FILE"
  printf 'Invoke: ./sagemaker/manage.sh invoke\n'
  printf 'Logs:   ./sagemaker/manage.sh logs\n'
  printf 'Delete: ./sagemaker/manage.sh cleanup\n'
}

status() {
  require_command aws
  load_state
  aws_cli sagemaker describe-endpoint \
    --endpoint-name "$ENDPOINT_NAME" \
    --query '{EndpointName:EndpointName,Status:EndpointStatus,FailureReason:FailureReason,Created:CreationTime,Updated:LastModifiedTime}'
}

invoke() {
  require_command aws
  load_state
  local request_file="${1:-$DEFAULT_REQUEST}"
  local output_file="${2:-/tmp/laya-sagemaker-response.json}"
  [[ -f "$request_file" ]] || die "Request file not found: $request_file"

  aws_cli sagemaker-runtime invoke-endpoint \
    --endpoint-name "$ENDPOINT_NAME" \
    --content-type application/json \
    --body "fileb://${request_file}" \
    --cli-binary-format raw-in-base64-out \
    "$output_file"

  printf '\nResponse body (%s):\n' "$output_file"
  python3 -m json.tool "$output_file" 2>/dev/null || cat "$output_file"
}

logs() {
  require_command aws
  load_state
  local since="${1:-1h}"
  aws_cli logs tail "/aws/sagemaker/Endpoints/${ENDPOINT_NAME}" --since "$since" --follow
}

cleanup() {
  require_command aws
  load_state
  local failed=0 result

  if resource_exists sagemaker describe-endpoint --endpoint-name "$ENDPOINT_NAME"; then
    printf 'Deleting endpoint %s...\n' "$ENDPOINT_NAME"
    aws_cli sagemaker delete-endpoint --endpoint-name "$ENDPOINT_NAME" || failed=1
    aws_cli sagemaker wait endpoint-deleted --endpoint-name "$ENDPOINT_NAME" || failed=1
  else
    result=$?
    ((result == 1)) || failed=1
  fi

  if resource_exists sagemaker describe-endpoint-config --endpoint-config-name "$ENDPOINT_CONFIG_NAME"; then
    printf 'Deleting endpoint configuration %s...\n' "$ENDPOINT_CONFIG_NAME"
    aws_cli sagemaker delete-endpoint-config --endpoint-config-name "$ENDPOINT_CONFIG_NAME" || failed=1
  else
    result=$?
    ((result == 1)) || failed=1
  fi

  if resource_exists sagemaker describe-model --model-name "$MODEL_NAME"; then
    printf 'Deleting model %s...\n' "$MODEL_NAME"
    aws_cli sagemaker delete-model --model-name "$MODEL_NAME" || failed=1
  else
    result=$?
    ((result == 1)) || failed=1
  fi

  if [[ "${DELETE_ECR_REPOSITORY:-0}" == "1" ]]; then
    printf 'Deleting ECR repository %s...\n' "$ECR_REPOSITORY"
    aws_cli ecr delete-repository --repository-name "$ECR_REPOSITORY" --force >/dev/null || failed=1
  else
    printf 'Keeping ECR repository %s. Set DELETE_ECR_REPOSITORY=1 to remove it.\n' "$ECR_REPOSITORY"
  fi

  if ((failed)); then
    die "Cleanup was incomplete. State retained at $STATE_FILE"
  fi
  rm -f "$STATE_FILE"
  printf 'Cleanup complete.\n'
}

command_name="${1:-}"
shift || true
case "$command_name" in
  deploy) deploy "$@" ;;
  status) status "$@" ;;
  invoke) invoke "$@" ;;
  logs) logs "$@" ;;
  cleanup) cleanup "$@" ;;
  -h|--help|help|'') usage ;;
  *) usage >&2; die "Unknown command: $command_name" ;;
esac
